#
# [ Database Configuration Section ]
#

spring:
  datasource:
    url: jdbc:postgresql://172.30.55.109:5432/testdb
    username: test
    password: test
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 9095


